# Generated by Django 5.1.2 on 2024-11-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DumpingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('organic', 'Organic'), ('recyclable', 'Recyclable'), ('hazardous', 'Hazardous')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_type', models.CharField(choices=[('organic', 'Organic'), ('recyclable', 'Recyclable'), ('hazardous', 'Hazardous')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('current_fill_level', models.IntegerField()),
                ('detected_waste_type', models.CharField(choices=[('organic', 'Organic'), ('recyclable', 'Recyclable'), ('hazardous', 'Hazardous')], max_length=20)),
                ('fill_status', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('en route', 'En Route'), ('collecting', 'Collecting')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WastePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dumpingarea')),
            ],
        ),
    ]
