# Generated by Django 5.1.2 on 2024-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
